webapp/routes/donate.py
from webapp.utils.tasks import new_donation_email
from webapp.utils.tools import convert_currency_symbol, generate_string
from webapp.forms import MakeDonationForm
from webapp.models import User, Donation
from flask import Blueprint, abort, render_template, flash, get_flashed_messages, jsonify, request, redirect, url_for, session

donate_bp = Blueprint("donate", __name__)

@donate_bp.route('/@<string:username>/donate', methods=['GET'])
def donate(username):
    user = User().fetch_user_supply_username(username)
    
    if not user:
        return abort(404)
    
    ## User can only access the pay donation page before they've paid. Then the session is removed
    if (session.get('donation_tracker')) and (session['donation_tracker'] > 2):
        session.pop('donation_session')

    return render_template('/shop/donate.html', user=user, form=MakeDonationForm(), flashed_message=get_flashed_messages())

@donate_bp.route('/donation/create/payment', methods=['POST'])
def create_donation() -> jsonify:
    form = MakeDonationForm()
    
    if not form.validate_on_submit():
        return jsonify({'Success':'Failure', 'error' : list(form.errors.values())[0]}), 400

    session['donation_session'] = generate_string(40)

    add_donation = Donation().add(request.form, request.referrer)

    if not all(add_donation):
        return jsonify({'Success':'Failure', 'error' : str(add_donation[1])}), 400

    session['donation_tracker'] = 1
    
    return jsonify({'success':'True', 'Payment':str(add_donation['payment']), 'address':str(add_donation['address']), 'donation_id' : add_donation['donation_id'], 'amount' : add_donation['amount']}), 200

@donate_bp.route('/donation/check/<string:donation_id>', methods=['GET'])
def donation_check(donation_id):
    token = request.args.get('token')
    
    if (not session.get('donation_session')) or (not token):
        return abort(404)

    donation = Donation().fetch_donation(donation_id)
    
    if not donation:
        return abort(404)
    
    user = User().query.filter_by(uuid=donation.user).first()

    if request.args.get('payment_timeout'):
        flash(['Payment timeout. Donation cancelled.'])
        return redirect(url_for('donate.donate', username=user.username)), 302

    if donation.status == 'Completed':
        flash([f'You successfully donated {convert_currency_symbol(user.settings.currency)}{float(donation.amount):.2f} to {user.username}'])
        return redirect(url_for('donate.donate', username=user.username))

    if donation.payment_method == 'paypal':
       paypal_payment = Donation().validate_paypal_donation(donation_id, token)
       
       if not paypal_payment:
           return redirect(url_for('donate.donate', username=user.username))
            
    elif donation.payment_method == 'stripe':
        stripe_payment = Donation().validate_stripe_donation(donation_id, request.args.get('intent'))
        
        if not stripe_payment:
            return redirect(url_for('donate.donate', username=user.username))

    else:
        check_crypto_transactions = Donation().validate_crypto_donation(donation.donation_payment.transaction_id)
        
        if not check_crypto_transactions:
            return jsonify(check_crypto_transactions)

        else:
            session['donation_tracker'] =+1

    new_donation_email.apply_async(args=[user.email, f'{convert_currency_symbol(user.settings.currency)}{donation.amount}'])

    flash([f'You successfully donated {convert_currency_symbol(user.settings.currency)}{float(donation.amount):.2f} to {user.username}'])
    return redirect(url_for('donate.donate', username=user.username)), 302
        
@donate_bp.route('/donation/cancel/<string:donation_id>', methods=['GET'])
def cancel_donation(donation_id):
    cancel_donation = Donation().cancel_donation(donation_id)
    
    if not cancel_donation:
        return abort(404)
    
    flash(['Donation Cancelled'])
    return redirect(url_for('donate.donate', username=cancel_donation))

webapp/routes/main.py
from flask import Flask, Blueprint, render_template

main_bp = Blueprint("main", __name__)

@main_bp.route('/', methods=['GET'])
def index():
    return render_template('/main/index.html')

@main_bp.route('/features', methods=['GET'])
def features():
    return render_template('/main/features.html')

@main_bp.route('/pricing', methods=['GET'])
def pricing():
    return render_template('/main/pricing.html')

webapp/routes/order.py
from webapp.forms import PurchaseProduct
from webapp.models import Order, Coupon, User, Product, Attachment
from webapp.payments.paypal import capture_paypal_order, get_paypal_order
from webapp.utils.uploads import download_file
from webapp.utils.tasks import leave_feedback
from flask import Blueprint, request, redirect, url_for, flash, render_template, get_flashed_messages, abort, Response, session
from os import environ

order_bp = Blueprint("order", __name__)

@order_bp.route('/create/order', methods=['POST'])
def create_order() -> redirect:
    form = PurchaseProduct()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(request.referrer)

    if request.form.get('coupon_code') != '':
        if not Coupon().check_coupon(request.form):
            flash(['Coupon is invalid. Please try again'])
            return redirect(request.referrer)

    new_order = Order().add(request.form, request.headers.get('User-Agent'))

    if False in new_order:
        flash([new_order[1]])
        return redirect(request.referrer)

    if new_order['payment_method'] == 'paypal':
        return redirect(new_order['payment_address'])
    
    return redirect(url_for('order.track_order', order_id=new_order))

@order_bp.route('/order/<string:order_id>', methods=['GET'])
def track_order(order_id) -> render_template:
    fetch_order = Order().fetch_order(order_id)
    
    if not fetch_order:
        return abort(404)
    
    return render_template('/shop/order.html', order=fetch_order, flashed_message=get_flashed_messages(), user=User().fetch_user_supply_uuid(fetch_order.user), product=Product().fetch_product(fetch_order.product_id, fetch_order.user))

@order_bp.route('/order/payment/complete/<string:order_id>', methods=['GET'])
def payment_complete(order_id):
    ## this needs to be rewritten to take into account stripe and crypto payments
    token = request.args.get('token')
    payer_id = request.args.get('PayerID')
    
    order = Order().fetch_order(order_id)
    
    if not order:
        return abort(404)
    
    if order.payment.transaction_id != token:
        return abort(404)
    
    if order.status != 'Paid':
        capture_paypal_order(token)
        check_order = get_paypal_order(token)
    
        if check_order['payment_status'] == 'COMPLETED':
            order.status = 'Paid'
            deliver_goods = Product().deliver_product(order.product_id, order_id, order.quantity, order.customer.email)
            leave_feedback.apply_async(args=[order.customer.email, User().fetch_user_supply_uuid(order.user).username, order_id, order.order_hash], countdown=120)

        if not order.customer.email:
            order.customer.email = check_order['buyer_email']
        
        order.update()

            
    return redirect(url_for('order.track_order', order_id=order_id))

@order_bp.route('/order/<string:order_id>/download/<string:attachment_id>', methods=['GET'])
def download_attachment(order_id, attachment_id):
    order = Order().fetch_order(order_id)
    
    if (not order) or (order.status != 'Completed'):
        return abort(404)

    attachment = Attachment().fetch_attachment(attachment_id)
    fetch_file = download_file(attachment.attachment_filename, environ.get('AWS_ATTACHMENTS'))
    
    return Response(
            fetch_file['file'],
            mimetype='text/plain',
            headers={"Content-Disposition": f"attachment;filename={attachment.original_attachment_filename}"}
    )

    
    
    
    
    
        
    
    

webapp/routes/shop.py
from webapp.forms import PurchaseProduct, StoreContact, TicketReply, FeedbackForm
from webapp.models import User, Product, Coupon, Ticket, TicketMessage, Order, Feedback
import webapp.utils.tasks as task
from flask import Blueprint, abort, render_template, get_flashed_messages, jsonify, request, flash, get_flashed_messages, redirect, url_for, session

shop_bp = Blueprint("shop", __name__)

@shop_bp.route('/@<string:username>', methods=['GET'])
def shop(username):
    user = User().fetch_user_supply_username(username)
    
    if not user:
        return abort(404)
    
    return render_template('/shop/shop.html', user=user, flashed_message=get_flashed_messages())

@shop_bp.route('/@<string:username>/category/<string:category>', methods=['GET'])
def shop_category(username, category):
    user = User().fetch_user_supply_username(username)

    if not user:
        return abort(404)

    return render_template('/shop/shop-category.html', user=user, category=category.replace('-', ' '))

@shop_bp.route('/@<string:username>/contact', methods=['GET'])
def open_ticket(username):
    user = User().fetch_user_supply_username(username)

    if not user:
        return abort(404)

    return render_template('/shop/contact.html', user=user, form=StoreContact(), flashed_message=get_flashed_messages())

@shop_bp.route('/@<string:username>/contact/submit', methods=['POST'])
def submit_ticket(username):
    form = StoreContact()

    user = User().fetch_user_supply_username(username)

    if not user:
        return abort(404)

    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('shop.open_ticket', username=username))

    Ticket().add(request.form, username)

    flash(['Your message has been sent.'])
    return redirect(url_for('shop.shop', username=username))

@shop_bp.route('/@<string:username>/ticket/<string:email>/<string:ticket_id>', methods=['GET'])
def customer_ticket(username, email, ticket_id):
    ticket = Ticket().fetch_customer_ticket(username, email, ticket_id)
    user = User().fetch_user_supply_uuid(ticket.user_id)

    if not ticket:
        return abort(404)

    return render_template('/shop/view-ticket.html', ticket=ticket, user=user, form=TicketReply(), flashed_message=get_flashed_messages())

@shop_bp.route('/ticket/<string:ticket_id>/submit', methods=['POST'])
def customer_ticket_reply(ticket_id):
    if Ticket().fetch_ticket_by_id(ticket_id) == 'Closed':
        return abort(404)
    
    form = TicketReply()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(request.referrer)
    
    TicketMessage().add_customer_message(ticket_id, request.form.get('message'))
   
    return redirect(request.referrer)

@shop_bp.route('/@<string:username>/<string:product_id>', methods=['GET'])
def product_page(username, product_id):
    form = PurchaseProduct()
    
    user = User().fetch_user_supply_username(username)
    product = Product().fetch_product(product_id, user.uuid)
    
    if (not product) or (product.user != user.uuid):
        return abort(404)

    form.product_id.data = product.id
    
    return render_template('/shop/product-page.html', product=product, user=user, form=form, flashed_message=get_flashed_messages())

@shop_bp.route('/product/coupon/check', methods=['POST'])
def check_coupon():
    check = Coupon().check_coupon(request.form)
    if not check:
        return jsonify({'Success':'False'}), 400
    else:
        return jsonify({'Success':'True', 'Discount':f'0.{check}'}), 200

@shop_bp.route('/@<string:username>/order/<string:order_id>/<string:order_hash>/feedback', methods=['GET'])
def leave_feedback(username, order_id, order_hash):
    order = Order().fetch_order(order_id)
    
    if (not order) or (order.order_hash != order_hash):
        return abort(404)
    
    return render_template('/shop/leave-feedback.html', user=User().fetch_user_supply_username(username), form=FeedbackForm(), order_id=order_id, order_hash=order_hash)

@shop_bp.route('/@<string:username>/order/<string:order_id>/<string:order_hash>/feedback/submit', methods=['POST'])
def submit_feedback(username, order_id, order_hash):

    form = FeedbackForm()

    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(request.referrer)

    order = Order().fetch_order(order_id)

    if (not order) or (order.order_hash != order_hash):
        return abort(404)

    feedback = Feedback().fetch_feedback(order.id)

    if not feedback:
        Feedback().add(request.form, order.id, order.user)
        flash(['Feedback Submitted'])

        return redirect(url_for('shop.shop', username=User().fetch_user_supply_uuid(order.user).username))

    Feedback().update_feedback(order.id, request.form)

    flash(['Feedback successfully updated.'])
    return redirect(url_for('shop.shop', username=User().fetch_user_supply_uuid(order.user).username))

@shop_bp.route('/@<string:username>/feedback', methods=['GET'])
def shop_feedback(username):
    user = User().fetch_user_supply_username(username)
    if not user:
        return abort(404)

    return render_template('/shop/feedback.html', feedback=Feedback().fetch_all_feedback(user.uuid), user=user)

webapp/templates/shop/donate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for('static', filename='styles/shop.css')}}" type="text/css" rel="stylesheet">
    <script src="https://js.stripe.com/v3/"></script>
    <title>Sellit - Donate to {{user.username}}</title>
</head>
<body class="grey-background" onload="donationsStatus()">
    <div class="not-accepting-donations">
        <p>{{user.username}} is not currently accepting donations</p>
    </div>
    <input type="hidden" id="donations_enabled" data_donations_enabled="{{user.settings.donations}}">
    <div class="donate-page">
        <div class="donate-page-block">
            <div class="donate-header">
                <h5>Donation</h5>
                <div class="powered-by">
                    <span>
                        Powered By
                    </span>
                    <a target="_blank" href="{{url_for('main.index')}}">
                        <img src="{{url_for('static', filename='img/logos/icon-only-light-background.png')}}" height="20" width="20">
                    </a>
                </div>
            </div>
            <div class="donate-main-content">
                <h3>Donate to <b>{{user.username}}</b></h3>
                <div class="donation-preset-buttons">
                    {% set currency = user.settings.currency|replace('GBP', '£')|replace('USD', '%')|replace('EUR', '€')%}
                    <button type="button" data-amount='{{user.settings.minimum_donation}}' class="btn btn-user-donation btn-primary btn-donate-one" onclick="setDonationAmount('.btn-donate-one')">
                    {{currency}}{{ "%.2f"|format(user.settings.minimum_donation|float)}}
                    </button>
                    {% set value = user.settings.minimum_donation | float * 2|round %}
                    <button type="button" data-amount="{{value}}" class="btn btn-user-donation btn-donate-two" onclick="setDonationAmount('.btn-donate-two')">
                        {{currency}}{{ "%.2f"|format(value) }}
                    </button>
                    {% set value = user.settings.minimum_donation | float * 3|round %}
                    <button type="button" data-amount="{{value}}" class="btn btn-user-donation btn-donate-three" onclick="setDonationAmount('.btn-donate-three')">
                        {{currency}}{{ "%.2f"|format(value) }}
                    </button>
                </div>
                <div class="donation-amount-input">
                    <p class="donation-currency">{{currency}}</p>
                    {{form.amount(value="%.2f"|format(user.settings.minimum_donation|float), min=user.settings.minimum_donation, data_min=user.settings.minimum_donation, onchange="checkDonationAmount()")}}
                </div>
                <hr class="donate-page-linebreak">
            <div class="donation-message">
                <div class="leave-message">
                    {{form.leave_message(onclick="showDonationMessageContent()", value='n')}}
                    <span>Leave A Message</span>
                    <div class="leave-message-content">
                        {{form.name(value='Anonymous')}}
                        {{form.message}}
                        <p id="donation-message-required">
                            Donation message is required. If you would prefer not leave a message, then please untick the checkbox
                        </p>
                    </div>
                </div>
            </div>
            <div class="continue-with-donation">
                <button data-username="{{user.username}}" data-currency="{{currency}}" type="button" onclick="continueWithDonation()" class="btn btn-primary btn-donation-continue">CONTINUE</button>
            </div>
            </div>
            <div class="donate-payment-methods">
                <h3 id="donation-amount-header"></h3>
                <div class="awaiting-payment">
                    <div class="awaiting-payment-left">
                        <img src="{{url_for('static', filename='img/icons/loading-spinner.svg')}}" height="20" width="20" id="awaiting-payment-spinner">
                        <span id="awaiting-payment-text">Awaiting Payment</span>
                    </div>
                    <div class="awaiting-payment-right">
                        <span id="awaiting-payment-timer">15:00</span>
                    </div>
                </div>
                <div class="crypto-donation-amount-tracker">
                    <p>
                        <span id="received-crypto-amount">0</span>
                        /
                        <span id="total-crypto-amount"></span>
                    </p>
                </div>
                <div class="payment-block-options">
                    {% if user.payment_methods.stripe %}
                        <div class="payment-block-product-page" onclick="setPaymentMethod('stripe')">
                            <button type="button" class="btn btn-payment btn-payment-inactive btn-payment-stripe"><img src="{{url_for('static', filename='img/icons/credit-card.svg')}}" height="25" width="25"></button>
                        </div>
                    {% endif %}
                    
                    {% if user.payment_methods.paypal %}
                        <div class="payment-block-product-page" onclick="setPaymentMethod('paypal')">
                            <button type="button" class="btn btn-payment btn-payment-inactive btn-payment-paypal"><img src="{{url_for('static', filename='img/icons/paypal.svg')}}" height="25" width="25"></button>
                        </div>
                    {% endif %}

                    {% if user.payment_methods.BTC %}
                        <div class="payment-block-product-page" onclick="setPaymentMethod('BTC')">
                            <button type="button" class="btn btn-payment btn-payment-inactive btn-payment-BTC"><img src="{{url_for('static', filename='img/icons/bitcoin.svg')}}" height="25" width="25"></button>
                        </div>
                    {% endif %}
                    
                    {% if user.payment_methods.ETH %}
                        <div class="payment-block-product-page" onclick="setPaymentMethod('ETH')">
                            <button type="button" class="btn btn-payment btn-payment-inactive btn-payment-ETH"><img src="{{url_for('static', filename='img/icons/ethereum.svg')}}" height="25" width="25"></button>
                        </div>
                    {% endif %}

                    {% if user.payment_methods.LTC %}
                        <div class="payment-block-product-page" onclick="setPaymentMethod('LTC')">
                            <button type="button" class="btn btn-payment btn-payment-inactive btn-payment-LTC"><img src="{{url_for('static', filename='img/icons/litecoin.svg')}}" height="25" width="25"></button>
                        </div>
                    {% endif %}
                    {% if user.payment_methods.LTCT %}
                        <div class="payment-block-product-page" onclick="setPaymentMethod('LTCT')">
                            <button type="button" class="btn btn-payment btn-payment-inactive btn-payment-LTC"><img src="{{url_for('static', filename='img/icons/litecoin.svg')}}" height="25" width="25"></button>
                        </div>
                    {% endif %}

                    {#{% if (not user.payment_methods.stripe) and (not user.payment_methods.paypal) and (not user.payment_methods.BTC) and (not user.payment_methods.ETH) and (not user.payment_methods.LTC) %}
                        <h4 id="no-payment-methods">{{user.username}} has no active payment methods</h4>
                    {% endif %}#}

                    {{form.payment_method(id='payment_method')}}
                    {{form.csrf_token}}
                    {{form.uuid(value=user.uuid)}}
                    <div class="product-buttons">
                        <button type="button" onclick="returnToDonation()" class="btn btn-back">Back</button>
                        {% if user.payment_methods !=[] %}
                            <button id="payment-block-continue" type="submit" onclick="makeDonation()" class="btn btn-primary donation-block-continue">
                                <span id="make-payment-text">Make Payment</span>
                                <img class="donation-loading-spinner" src="{{url_for('static', filename='img/icons/loading-spinner.svg')}}" width="25" height="25">
                            </button>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="pay-donation-stripe">
                <form id="payment-form">
                    <div id="card-element"></div>
                    <button id="stripe-submit">
                        <img id="stripe-processing-payment" class="donation-loading-spinner" src="{{url_for('static', filename='img/icons/loading-spinner.svg')}}" height="25" width="25">
                        <span id="pay-now-text">Pay now</span>
                    </button>
                    <p id="card-error" role="alert"></p>
                </form>
                <p class="stripe-payment-error"></p>
                <div class="cancel-donation" onclick="cancelDonation()">
                    <button type="button" class="btn btn-cancel-donation">Cancel Donation</button>
                </div>
            </div>

            <div class="pay-donation-crypto">
                <h3 id="crypto-pay-amount"></h3>
                <div class="crypto-pay-qr">

                </div>
                <div class="cancel-donation" onclick="cancelDonation()">
                    <button type="button" class="btn btn-cancel-donation">Cancel Donation</button>
                </div>
            </div>
        </div>
        <p class="flashed-error-donation"></p>
            {% for item in flashed_message %}
                {% if 'successfully' in item[0] %}
                    <p class="donation-flashed-success">
                        {{item[0]}}
                    </p>
                {% else %}
                    <p class="flashed-error">{{item[0]}}</p>
                {% endif %}
            {% endfor %}
    </div>
    <script src="{{url_for('static', filename='scripts/shop.js')}}"></script>
    <script src="{{url_for('static', filename='scripts/qrcode.min.js')}}"></script>
</body>

webapp/templates/shop/feedback.html
{% extends 'base/shop.html' %}
{% block username %}Sellit - @{{user.username}}{% endblock %}
{% block content %}
<div class="main-container">
    <div class="feedback-blocks-wrapper">
        {% for i in feedback %}
            <div class="feedback-block">
                <h3>Rating: {{i.rating}}</h3>
                <div class="feedback-content">
                    {{i.comment}}
                </div>
                <div class="feedback-date">
                    {{i.timestamp|timestamp_to_human}}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

webapp/templates/shop/leave-feedback.html
{% extends 'base/shop.html' %}
{% block username %}Sellit - @{{user.username}}{% endblock %}
{% block content %}
    <div class="main-container feedback-wrapper">
        <form method="POST" action="{{url_for('shop.submit_feedback', username=user.username, order_id=order_id, order_hash=order_hash)}}">
            <div class="form-control">
                <label for="rating">
                    Rating
                </label>
                <div class="rating-wrapper">
                    <img id="1" src="{{url_for('static', filename='img/icons/star.svg')}}" width="20">
                    <img id="2" src="{{url_for('static', filename='img/icons/star.svg')}}" width="20">
                    <img id="3" src="{{url_for('static', filename='img/icons/star.svg')}}" width="20">
                    <img id="4" src="{{url_for('static', filename='img/icons/star.svg')}}" width="20">
                    <img id="5" src="{{url_for('static', filename='img/icons/star.svg')}}" width="20">
                </div>
            </div>
            <div class="form-control">
                <label for="comment">
                    Comment
                </label>
                {{form.comment}}
                {{form.csrf_token}}
            </div>
            
            {{form.rating(id="rating")}}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

webapp/templates/shop/shop-category.html
{% extends 'base/shop.html' %}
{% block username %}Sellit - @{{user.username}}{% endblock %}
{% block content %}
    <!-- user categories -->
    {% if user.categories != [] %}
        <div class="shop-categories main-container">
            <ul class="inline-list category-list">
                <a href="{{url_for('shop.shop', username=user.username)}}">
                    <li>
                        All
                    </li>
                </a>
                {% set category_list = [] %}
                {% for item in user.categories %}
                    {% for product in user.products %}
                        {% for cat in product.product_category %}
                            {% if item.category_name == cat.category_name %}
                                {% if item.category_name not in category_list %}
                                    <a href="{{url_for('shop.shop_category', username=user.username, category=item.category_name.replace(' ', '-'))}}">
                                        <li>
                                            {{item.category_name}}
                                        </li>
                                    </a>
                                    {% set tmp = category_list.append(item.category_name) %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <!-- user categories -->

    <!-- user products -->
    <div class="products-block main-container">
        {% if user.products != [] %}
            {% for item in user.products %}
                {% for fetch_category in item.product_category %}
                    {% if fetch_category.category_name == category %}
                        <a href="{{url_for('shop.product_page', username=user.username, product_id=item.id) | replace('%40', '@')}}">
                            <div class="mini-product-container form-control">
                                <img src="https://sellitpi.s3.eu-west-2.amazonaws.com/default.png">
                                <div class="mini-product-details">
                                    <h4>{{item.name}}</h4>
                                    <p>{{item.currency}}{{item.price}}</p>
                                </div>
                                <button type="button" class="btn btn-view-product">View Product</button>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% else %}
            <div class="user-no-products">
                <h2>{{user.username}} has no products yet!</h2>
            </div>
        {% endif %}
    </div>
    <!-- user products -->
{% endblock %}

webapp/templates/shop/shop.html
{% extends 'base/shop.html' %}
{% block username %}Sellit - @{{user.username}}{% endblock %}
{% block content %}
    <!-- user categories -->
    {% if user.categories != [] %}
        <div class="shop-categories main-container">
            <ul class="inline-list category-list">
                <a href="{{url_for('shop.shop', username=user.username)}}">
                    <li>
                        All
                    </li>
                </a>
                {% set category_list = [] %}
                {% for item in user.categories %}
                    {% for product in user.products %}
                        {% for cat in product.product_category %}
                            {% if item.category_name == cat.category_name %}
                                {% if item.category_name not in category_list %}
                                    <a href="{{url_for('shop.shop_category', username=user.username, category=item.category_name.replace(' ', '-'))}}">
                                        <li>
                                            {{item.category_name}}
                                        </li>
                                    </a>
                                    {% set tmp = category_list.append(item.category_name) %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <!-- user categories -->

    <!-- user products -->
    <div class="products-block main-container">
        {% if user.products != [] %}
            {% for item in user.products %}
                <a href="{{url_for('shop.product_page', username=user.username, product_id=item.id) | replace('%40', '@')}}">
                    <div class="mini-product-container form-control">
                        <img src="https://sellitpi.s3.eu-west-2.amazonaws.com/default.png">
                        <div class="mini-product-details">
                            <h4>{{item.name}}</h4>
                            <p>{{item.currency}}{{item.price}}</p>
                        </div>
                        <button type="button" class="btn btn-view-product">View Product</button>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <div class="user-no-products">
                <h2>{{user.username}} has no products yet!</h2>
            </div>
        {% endif %}
    </div>
    <!-- user products -->
{% endblock %}

webapp/templates/shop/track-donation.html
track donation