webapp/routes/auth.py
from webapp.utils.login_decorator import loggedout_required, developer_required
from webapp.utils.tools import validate_dob
from webapp.utils.regex import email_regex
from webapp.forms import RegisterForm, LoginForm, PasswordResetForm
from webapp.models import User, Verification
from flask import Blueprint, render_template, url_for, flash, get_flashed_messages, redirect, request, abort
from flask_login import login_user, logout_user

auth_bp = Blueprint("auth", __name__)

@auth_bp.route('/register', methods=['GET'], subdomain='auth')
@developer_required
@loggedout_required
def register() -> render_template:
    return render_template('/auth/register.html', form=RegisterForm(), flashed_message=get_flashed_messages())

@auth_bp.route('/register/user', methods=['POST'], subdomain='auth')
@developer_required
@loggedout_required
def register_user() -> redirect:
    form = RegisterForm()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('auth.register'))

    if User().query.filter_by(email=request.form.get('email')).first():
        flash(['''Email is already registered. Please use a different email, or login to continue'''])
        return redirect(url_for('auth.register'))

    if not email_regex(request.form.get('email')):
        flash(['Please enter a valid email'])
        return redirect(url_for('auth.register'))

    if User().query.filter_by(username=request.form.get('username')).first():
        flash(['Username is taken. Please choose another username.'])
        return redirect(url_for('auth.register'))

    if not validate_dob(request.form.get('date_of_birth')):
        flash(['You must be at least 13 years old to use Sellit.'])
        return redirect(url_for('auth.register'))

    User().create_user(request.form)
    
    flash(['Account created. Please check your email to activate your account'])
    return redirect(url_for('auth.login'))

@auth_bp.route('/email/verify/<string:email_code>', methods=['GET'], subdomain='auth')
@developer_required
@loggedout_required
def verify_email(email_code) -> redirect:
    if not User().activate_account(email_code):
        return abort(404)
    
    flash(['Your account has been verified. Please login to continue'])
    return redirect(url_for('auth.login'))

@auth_bp.route('/login', methods=['GET'], subdomain='auth')
@developer_required
@loggedout_required
def login() -> render_template:    
    return render_template('/auth/login.html', flashed_message=get_flashed_messages(), form=LoginForm())

@auth_bp.route('/login/user', methods=['POST'], subdomain='auth')
@developer_required
@loggedout_required
def login_attempt() -> redirect:
    form = LoginForm()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('auth.login'))

    query = User().check_credentials(request.form.get('email'), request.form.get('password'))
    
    if not query:
        flash(['Incorrect login details'])
        return redirect(url_for('auth.login'))
    
    if query.verification.email_code:
        update_code = Verification().update_verification(query.uuid)

        flash(['Your account has not been activated. Another email has been sent'])
        return redirect(url_for('auth.login'))
    
    login_user(query)
    return redirect(url_for('dashboard.home'))

@auth_bp.route('/logout', methods=['GET'], subdomain='auth')
@developer_required
def logout() -> render_template:
    logout_user()
    return redirect(url_for('auth.login'))

@auth_bp.route('/forgotten/password', methods=['GET'], subdomain='auth')
@developer_required
@loggedout_required
def forgotten_password() -> render_template:
    return render_template('/auth/reset-password.html', form=PasswordResetForm(), flashed_message=get_flashed_messages())

@auth_bp.route('/reset/password/submit', methods=['POST'], subdomain='auth')
@developer_required
@loggedout_required
def check_email_password() -> redirect:
    form = PasswordResetForm()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
    
    User().password_reset(request.form.get('email'))
    
    flash(['If your email exists, you will receive a password reset email shortly'])
    return redirect(url_for('auth.login'))

@auth_bp.route('/reset/password/<string:password_code>', methods=['GET'], subdomain='auth')
@developer_required
@loggedout_required
def reset_password(password_code) -> redirect:
    if not User().set_new_password(password_code):
        flash(['Something went wrong. Please try again'])
        return redirect(url_for('auth.forgotten_password'))
    
    flash(['Your password has been successfully reset. Check your email for your new password'])
    return redirect(url_for('auth.login'))

webapp/routes/developer.py
from flask import Flask, Blueprint, render_template

developer_bp = Blueprint("developer", __name__)

@developer_bp.route('/', methods=['GET'], subdomain='developer')
def index():
    return render_template('/developer/index.html')

webapp/routes/main.py
from flask import Flask, Blueprint, render_template

main_bp = Blueprint("main", __name__)

@main_bp.route('/', methods=['GET'])
def index():
    return render_template('/main/index.html')

@main_bp.route('/features', methods=['GET'])
def features():
    return render_template('/main/features.html')

@main_bp.route('/pricing', methods=['GET'])
def pricing():
    return render_template('/main/pricing.html')

webapp/routes/shop.py
from webapp.forms import PurchaseProduct, StoreContact, TicketReply, FeedbackForm
from webapp.models import User, Product, Coupon, Ticket, TicketMessage, Order, Feedback
import webapp.utils.tasks as task
from flask import Blueprint, abort, render_template, get_flashed_messages, jsonify, request, flash, get_flashed_messages, redirect, url_for, session

shop_bp = Blueprint("shop", __name__)

@shop_bp.route('/@<string:username>', methods=['GET'])
def shop(username):
    user = User().fetch_user_supply_username(username)
    
    if not user:
        return abort(404)
    
    return render_template('/shop/shop.html', user=user, flashed_message=get_flashed_messages())

@shop_bp.route('/@<string:username>/category/<string:category>', methods=['GET'])
def shop_category(username, category):
    user = User().fetch_user_supply_username(username)

    if not user:
        return abort(404)

    return render_template('/shop/shop-category.html', user=user, category=category.replace('-', ' '))

@shop_bp.route('/@<string:username>/contact', methods=['GET'])
def open_ticket(username):
    user = User().fetch_user_supply_username(username)

    if not user:
        return abort(404)

    return render_template('/shop/contact.html', user=user, form=StoreContact(), flashed_message=get_flashed_messages())

@shop_bp.route('/@<string:username>/contact/submit', methods=['POST'])
def submit_ticket(username):
    form = StoreContact()

    user = User().fetch_user_supply_username(username)

    if not user:
        return abort(404)

    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('shop.open_ticket', username=username))

    Ticket().add(request.form, username)

    flash(['Your message has been sent.'])
    return redirect(url_for('shop.shop', username=username))

@shop_bp.route('/@<string:username>/ticket/<string:email>/<string:ticket_id>', methods=['GET'])
def customer_ticket(username, email, ticket_id):
    ticket = Ticket().fetch_customer_ticket(username, email, ticket_id)
    user = User().fetch_user_supply_uuid(ticket.user_id)

    if not ticket:
        return abort(404)

    return render_template('/shop/view-ticket.html', ticket=ticket, user=user, form=TicketReply(), flashed_message=get_flashed_messages())

@shop_bp.route('/ticket/<string:ticket_id>/submit', methods=['POST'])
def customer_ticket_reply(ticket_id):
    if Ticket().fetch_ticket_by_id(ticket_id) == 'Closed':
        return abort(404)
    
    form = TicketReply()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(request.referrer)
    
    TicketMessage().add_customer_message(ticket_id, request.form.get('message'))
   
    return redirect(request.referrer)

@shop_bp.route('/@<string:username>/<string:product_id>', methods=['GET'])
def product_page(username, product_id):
    form = PurchaseProduct()
    
    user = User().fetch_user_supply_username(username)
    product = Product().fetch_product(product_id, user.uuid)
    
    if (not product) or (product.user != user.uuid):
        return abort(404)

    form.product_id.data = product.id
    
    return render_template('/shop/product-page.html', product=product, user=user, form=form, flashed_message=get_flashed_messages())

@shop_bp.route('/product/coupon/check', methods=['POST'])
def check_coupon():
    check = Coupon().check_coupon(request.form)
    if not check:
        return jsonify({'Success':'False'}), 400
    else:
        return jsonify({'Success':'True', 'Discount':f'0.{check}'}), 200

@shop_bp.route('/@<string:username>/order/<string:order_id>/<string:order_hash>/feedback', methods=['GET'])
def leave_feedback(username, order_id, order_hash):
    order = Order().fetch_order(order_id)
    
    if (not order) or (order.order_hash != order_hash):
        return abort(404)
    
    return render_template('/shop/leave-feedback.html', user=User().fetch_user_supply_username(username), form=FeedbackForm(), order_id=order_id, order_hash=order_hash)

@shop_bp.route('/@<string:username>/order/<string:order_id>/<string:order_hash>/feedback/submit', methods=['POST'])
def submit_feedback(username, order_id, order_hash):

    form = FeedbackForm()

    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(request.referrer)

    order = Order().fetch_order(order_id)

    if (not order) or (order.order_hash != order_hash):
        return abort(404)

    feedback = Feedback().fetch_feedback(order.id)

    if not feedback:
        Feedback().add(request.form, order.id, order.user)
        flash(['Feedback Submitted'])

        return redirect(url_for('shop.shop', username=User().fetch_user_supply_uuid(order.user).username))

    Feedback().update_feedback(order.id, request.form)

    flash(['Feedback successfully updated.'])
    return redirect(url_for('shop.shop', username=User().fetch_user_supply_uuid(order.user).username))

@shop_bp.route('/@<string:username>/feedback', methods=['GET'])
def shop_feedback(username):
    user = User().fetch_user_supply_username(username)
    if not user:
        return abort(404)

    return render_template('/shop/feedback.html', feedback=Feedback().fetch_all_feedback(user.uuid), user=user)

webapp/templates/base/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for('static', filename='styles/auth.css')}}" type="text/css" rel="stylesheet">
    <link rel="icon" type="image" href="{{url_for('static', filename='img/icons/favicon.ico')}}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&family=Roboto:wght@300;400;500;700&display=swap&family=Inter:wght@300;400;500;700&display=swap" rel="stylesheet">
    <title>Sellit - {% block title %}{% endblock %}</title>
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <script src="{{url_for('static', filename='scripts/auth.js')}}"></script>
</body>
</html>

webapp/templates/base/dashboard-flashed-messages.html
{% if flashed_message != [] %}
    <div class="flashed-message-backend">
        {% for item in flashed_message %}
            {% if ('Something went wrong' in item[0]) or ('Coupon already exists' in item[0]) or ('Category already exists' in item[0]) or ('removed from the Blacklis' in item[0]) or("You can't delete" in item[0]) or ('This attachment has already been uploaded' in item[0]) or ('Invalid Email' in item[0]) or ('Passwords do not match' in item[0]) or ('Incorrect Password' in item[0]) or ('Please enter a valid IP Address' in item[0]) or ('Please enter a valid email' in item[0]) or ('Attachment too large' in item[0]) %}
                <div class="flashed-error">
                    {{item[0]}}
                </div>
            {% else %}
                <div class="flashed-success">
                    {{item[0]}}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

webapp/templates/base/dashboard-top-bar.html
<!-- top bar -->
<div class="dashboard-top-bar">
    <div class="mobile-menu-icon">
        <img onclick="showMobileMenu()" id="mobile-menu-icon" src="{{url_for('static', filename='img/icons/menu.svg')}}" height="20" width="20">
    </div>
    <div class="search-container">
        <img src="{{url_for('static', filename='img/icons/search.svg')}}" height="15" width="15">
        <input class="search-input" type="text" placeholder="Search...">
    </div>

    <div class="top-bar-right">
        <div class="top-bar-icons">
            <a href="{{url_for('shop.shop', username=current_user.get_username())}}">
                <img src="{{url_for('static', filename='img/icons/store.svg')}}" width="20" height="20">
            </a>
            <img src="{{url_for('static', filename='img/icons/bell.svg')}}" width="20" height="20">
        </div>

        <div class="top-bar-user-dropdown">
            <p>John Doe</p>
            <img src="{{url_for('static', filename='img/icons/down-arrow.svg')}}" onchange="openDropdown()" height="10" width="10" class="down-arrow-topbar">

            <!-- settings dropdown -->
            <div class="settings-dropdown">
                {#<div class="inline-flex settings-row">
                    <div class="switch-wrapper">
                        <label class="switch">
                            <input id="dark-mode" type="checkbox" disabled>
                                <span class="check-slider round"></span>
                            </label>
                    </div>
                    <p> Dark Mode </p>
                    <div class="dm-coming-soon">
                        Coming Soon
                    </div>
                </div>#}
                <div class="inline-flex settings-row">
                    <a href="{{url_for('dashboard.payment_methods')}}">
                        <div class="settings-row-last">
                            <img src="{{url_for('static', filename='img/icons/credit-card.svg')}}" width="25" height="25" class="settings-dropdown-icon">
                        </div>
                        <p>Payment Methods</p>
                    </a>
                    
                    
                </div>
                <div class="inline-flex settings-row">
                    <a href="{{url_for('dashboard.settings')}}">
                        <div class="settings-row-last">
                            <img src="{{url_for('static', filename='img/icons/gear.svg')}}" width="25" height="25" class="settings-dropdown-icon">
                        </div>
                        <p>Settings</p>
                    </a>
                    
                </div>
                <div class="inline-flex settings-row logout-row">
                    <a href="{{url_for('auth.logout')}}">
                        <div class="settings-row-last">
                            <img src="{{url_for('static', filename='img/icons/logout.svg')}}" width="25" height="25" class="settings-dropdown-icon" id="settings-logout">
                        </div>
                        <p class="logout-text">Log Out</p>
                    </a>
                    
                </div>
            </div>
            <!-- settings dropdown -->
        </div>
    </div>
</div>
<!-- top bar -->

webapp/templates/base/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for('static', filename='styles/back.css')}}" type="text/css" rel="stylesheet">
    <link rel="icon" type="image" href="{{url_for('static', filename='img/icons/favicon.ico')}}">
    <title>Sellit - {% block title %}{% endblock %}</title>
</head>
<body{% if active_page == 'coupons' %} onload="setStartDate()"{% endif %}>
    {% include 'base/dashboard-navigation.html' %}
    
    <main class="dashboard-main-content">
        {% include 'base/dashboard-top-bar.html' %}
        <!-- main content -->
        <div class="main-content">
            <div class="inprogress-animation">
                <span id="elem" class="slider"></span> 
            </div>
            {% include 'base/dashboard-flashed-messages.html' %}
            {% block content %}
            {% endblock %}
        </div>
        <!-- main content-->
    </main>
    
    <script src="{{url_for('static', filename='scripts/back.js')}}"></script>
    
    {% if active_page == 'analytics' %}
        <script src="{{url_for('static', filename='scripts/highcharts.js')}}"></script>
        <script src="{{url_for('static', filename='scripts/analytics.js')}}"></script>
    {% endif %}
    
    {% if (create_product == 'y') or (edit_product == 'y') %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.7.1/tinymce.min.js" integrity="sha512-RnlQJaTEHoOCt5dUTV0Oi0vOBMI9PjCU7m+VHoJ4xmhuUNcwnB5Iox1es+skLril1C3gHTLbeRepHs1RpSCLoQ==" crossorigin="anonymous"></script>
    {% endif %}
    
    {% if create_product == 'y' %}
        <script>
            createTextEditor('create-product-textarea')
        </script>
    {% endif %}
    
    {% if edit_product == 'y' %}
        <script>
            createTextEditor('create-product-textarea', `{{product.description|safe}}`);
            editProduct();
            document.querySelector('#description_value').value = `{{product.description|safe}}`;
            {% for item in product.product_category %}
                document.querySelector(`option[value="{{item.category_name}}"]`).setAttribute('selected', 'true');
            {% endfor %}
        </script>
    {% endif %}
    
    {% if active_page == 'settings_general' %}
        <script>
            preloadSettings('{{avatar}}')
        </script>
    {% endif %}
        
</body>
</html>

webapp/templates/base/front.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link type="image/gif" rel="icon" href="{{url_for('static', filename='img/favicons/favicon.ico')}}">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&family=Roboto:wght@300;400;500;700&display=swap&family=Inter:wght@300;400;500;700&display=swap" rel="stylesheet">
      <link href="{{url_for('static', filename='styles/front.css')}}" type="text/css" rel="stylesheet">
      <title>Sellit -{% block title %}{% endblock %}</title>
   </head>
   <body>
      <header>
         <div class="top-bar-message">
            <h4>Sellit is currently in development. Check back soon for further updates</h4>
         </div>
         <nav class="main-container">
            <div class="nav-left">
               <a href="{{url_for('main.index')}}">
                  <div class="nav-logo">
                     <img src="{{url_for('static', filename='img/logos/logo-purple.png')}}" id="nav-logo" width="100">
                  </div>
               </a>
            </div>
            <div class="nav-centre">
               <div class="nav-links">
                  <ul class="inline-list">
                     <a href="{{url_for('main.features')}}">
                        <li>
                           Features
                        </li>
                     </a>
                     <a href="{{url_for('main.pricing')}}">
                        <li>
                           Pricing
                        </li>
                     </a>
                     <a href="{{url_for('developer.index')}}">
                        <li>
                           Developer
                        </li>
                     </a>
                  </ul>
               </div>
            </div>
            <div class="nav-right">
               <div class="nav-auth">
                  <ul class="inline-list">
                     <li>
                        <a href="{{url_for('auth.login')}}">
                        Login
                        </a>
                     </li>
                     <span id="auth-seperator"> |</span>
                     <li>
                        <a href="{{url_for('auth.register')}}">
                        Register
                        </a>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="mobile-icon">
               <img id="hamburger-icon" onclick="openMobileMenu()" src="{{url_for('static', filename='img/icons/mobile-menu.svg')}}">
            </div>
            <div class="mobile-menu">
               <div class="mobile-nav-links">
                  <ul>
                     <a href="{{url_for('main.features')}}">
                        <li>
                           Features
                        </li>
                     </a>
                     <a href="{{url_for('main.pricing')}}">
                        <li>
                           Pricing
                        </li>
                     </a>
                     <a href="{{url_for('developer.index')}}">
                        <li>
                           Developer
                        </li>
                     </a>
                     <a href="{{url_for('auth.register')}}">
                        <li>
                           Register
                        </li>
                     </a>
                     <a href="{{url_for('auth.login')}}">
                        <li>
                           Login
                        </li>
                     </a>
                  </ul>
               </div>
            </div>
         </nav>
      </header>
      <main>
         {% block content %}
         {% endblock %}
      </main>
      <footer>
         <div class="footer-wrapper main-container">
            <div class="footer-block footer-block-company-info">
               <img src="{{url_for('static', filename='img/logos/logo-purple.png')}}" width="100">
               <p class="footer-site-description">
                  Sellit is an online eCommerce payment processing platform that lets you create your own store with a couple of clicks.
               </p>
            </div>
            <div class="footer-block">
               <h3 class="footer-heading">
                  Sellit
               </h3>
               <ul class="footer-list">
                  <li>
                     Features 
                  </li>
                  <li>
                     Pricing 
                  </li>
                  <li>
                     Developer 
                  </li>
               </ul>
            </div>
            <div class="footer-block">
               <h3 class="footer-heading">
                  Support
               </h3>
               <ul class="footer-list">
                  <li>
                     Documentation 
                  </li>
                  <li>
                     Guides
                  </li>
                  <li>
                     API Status 
                  </li>
               </ul>
            </div>
            <div class="footer-block">
               <h3 class="footer-heading">
                  Help
               </h3>
               <ul class="footer-list">
                  <li>
                     Twitter
                  </li>
                  <li>
                     Instagram
                  </li>
                  <li>
                     Live Chat
                  </li>
               </ul>
            </div>
            <div class="footer-block">
               <h3 class="footer-heading">
                  Company
               </h3>
               <ul class="footer-list">
                  <li>
                     About
                  </li>
                  <li>
                     Blog
                  </li>
                  <li>
                     Join The Team
                  </li>
               </ul>
            </div>
         </div>
         <div class="footer-bottom main-container">
            <span id="footer-copyright">Copyright 2021, Sellit Ecommerce All Rights Reserved.</span>
         </div>
      </footer>
      <script src="{{url_for('static', filename='scripts/front.js')}}"></script>
   </body>
</html>

webapp/templates/base/settings.html
{% extends 'base/dashboard.html' %}
{% block title %}Settings{% endblock %}
{% block content %}
    <div class="settings-wrapper">
        <div class="settings-left">
            <ul>
                <a href="{{url_for('dashboard.settings')}}">
                    <li {% if active_page == 'settings_general' %} class="setting-link-active" {% endif %}>
                        General
                    </li>
                </a>
                <a href="{{url_for('dashboard.security_settings')}}">
                    <li {% if active_page == 'settings_security' %} class="setting-link-active" {% endif %}>
                        Security
                    </li>
                </a>
                <a href="{{url_for('dashboard.payment_methods')}}">
                    <li id="settings-link-pm" {% if active_page == 'settings_payment_methods' %} class="setting-link-active" {% endif %}>
                        Payment Methods
                    </li>
                </a>

                <a href="{{url_for('dashboard.notification_settings')}}">
                    <li id="settings-link-pm" {% if active_page == 'settings_notifications' %} class="setting-link-active" {% endif %}>
                        Notifications
                    </li>
                </a>
                
            </ul>
        </div>
        <div class="settings-right">
            {% block settings_block %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

webapp/templates/base/shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for('static', filename='styles/shop.css')}}" type="text/css" rel="stylesheet">
    <link rel="icon" type="image" href="{{url_for('static', filename='img/icons/favicon.ico')}}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&family=Roboto:wght@300;400;500;700&display=swap&family=Inter:wght@300;400;500;700&display=swap" rel="stylesheet">
    <title>{% block username %} - {% endblock %} {% block title %}{% endblock %}</title>
</head>
<main>
    <div class="shop-header">
        <div class="main-container">
            <div class="shop-top-bar">
                <div class="shop-branding">
                    <img src="{{url_for('static', filename='img/logos/logo.png')}}" width="100">
                </div>
                {% if current_user.is_authenticated %}
                    <div class="visit-dashboard">
                        <a href="#">
                            <button type="button" class="btn-visit-dashboard">
                                Visit Dashboard
                            </button>
                        </a>
                    </div>
                {% endif %}
            </div>

            <div class="shop-user-block{% if active_page == 'product_page'%} hide-user-block{%endif%}">
                <img id="shop-img-avatar" width="200" src="https://sellit-avatars.s3.eu-west-2.amazonaws.com/default.png">

                <div class="shop-nav-links">
                    <ul class="inline-list">
                        <a href="{{url_for('shop.shop', username=user.username)}}">
                            <li>
                                Products
                            </li>
                        </a>
                        <a href="{{url_for('shop.shop_feedback', username=user.username)}}">
                            <li>
                                Feedback
                            </li>
                        </a>
                        <a href="{{url_for('shop.open_ticket', username=user.username)}}">
                            <li>
                                Contact
                            </li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
    {% include 'include/flashed_messages/shop.html' %}
    <script src="{{url_for('static', filename='scripts/shop.js')}}"></script>
</main>
</html>