webapp/routes/dashboard.py
from webapp.utils.login_decorator import login_required
from webapp.utils.uploads import download_file
from webapp.utils.regex import email_regex, ip_regex
from webapp.forms import SettingsForm, ProductForm, CategoryForm, AttachmentForm, CouponForm, BlacklistForm, SecurityForm, PaymentForm, DonationSettingsForm, TicketReply, SettingsNotificationsForm
from webapp.models import User, Setting, Category, Product, Attachment, Coupon, Blacklist, ProductCategory, PaymentMethod, Donation, ProductItem, Ticket, TicketMessage, EmailNotification, Order
from flask import Blueprint, render_template, url_for, redirect, request, flash, get_flashed_messages, abort, Response
from flask_login import current_user
from os import environ
from typing import Union

dashboard_bp = Blueprint("dashboard", __name__)

@dashboard_bp.route('/', methods=['GET'], subdomain='dashboard')
@login_required
def home() -> render_template:
    return render_template('/dashboard/dashboard.html')

@dashboard_bp.route('/settings', methods=['GET'], subdomain='dashboard')
@login_required
def settings() -> render_template:
    user = User().fetch_user_logged_in()
    
    form = SettingsForm()
    form.username.data = user.username
    form.email.data = user.email

    if user.settings.tawk_key:
        form.tawk_key.data = user.settings.tawk_key

    form.currency.data = user.settings.currency
    form.timezone.data = user.settings.timezone
    
    return render_template('/dashboard/settings.html', form=form, flashed_message=get_flashed_messages(), avatar=user.avatar.avatar_filename)

@dashboard_bp.route('/settings/update', methods=['POST'], subdomain='dashboard')
@login_required
def update_settings() -> redirect:
    form = SettingsForm()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('dashboard.settings'))

    Setting().update(request)
    
    flash(['Settings updated successfully'])
    return redirect(url_for('dashboard.settings'))

@dashboard_bp.route('/settings/security', methods=['GET'], subdomain='dashboard')
@login_required
def security_settings() -> render_template:
    return render_template('/dashboard/security.html', form=SecurityForm(), flashed_message=get_flashed_messages())

@dashboard_bp.route('/settings/security/update', methods=['POST'], subdomain='dashboard')
@login_required
def security_settings_update() -> render_template:
    form = SecurityForm()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('dashboard.security_settings'))

    if not User().update_password(request.form.get('current_password'), request.form.get('password')):
        flash(['Incorrect Password. Please try again'])
        return redirect(url_for('dashboard.security_settings'))

    flash(['Password successfully updated'])
    return redirect(url_for('dashboard.security_settings'))

@dashboard_bp.route('/settings/payment/methods', methods=['GET'], subdomain='dashboard')
@login_required
def payment_methods() -> render_template:
    form = PaymentForm()
    user = User().fetch_user_logged_in()
    
    form.paypal.data = user.payment_methods.paypal or ''
    form.paypal_delivery.data = user.payment_methods.paypal_delivery or ''
    form.BTC.data = user.payment_methods.BTC or ''
    form.ETH.data = user.payment_methods.ETH or ''
    form.LTC.data = user.payment_methods.LTC or ''

    return render_template('/dashboard/payment-methods.html', form=form, user=user, flashed_message=get_flashed_messages())

@dashboard_bp.route('/settings/payment/methods/submit', methods=['POST'], subdomain='dashboard')
@login_required
def payment_methods_update() -> redirect:
    form = PaymentForm()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('dashboard.payment_methods'))

    PaymentMethod().update_payment_methods(request.form)

    flash(['Payment Methods successfully updated'])
    return redirect(url_for('dashboard.payment_methods'))

@dashboard_bp.route('/settings/notifications', methods=['GET'], subdomain='dashboard')
@login_required
def notification_settings():
    form = SettingsNotificationsForm()
    notification = EmailNotification().fetch_notification_settings(current_user.get_id())
    
    form.new_order.checked = notification.new_order
    form.new_donation.checked = notification.new_donation
    form.new_feedback.checked = notification.new_feedback
    form.new_support_ticket.checked = notification.new_support_ticket
    form.support_ticket_reply.checked = notification.support_ticket_reply

    return render_template('/dashboard/settings-notification.html', form=form)

@dashboard_bp.route('/settings/notifications/update', methods=['POST'], subdomain='dashboard')
@login_required
def update_notification_settings():
    if not EmailNotification().update(request.form):
        flash(['Something went wrong. Please try again'])
        return redirect(url_for('dashboard.notification_settings'))

    flash(['Settings successfully updated'])
    return redirect(url_for('dashboard.notification_settings'))

@dashboard_bp.route('/donations', methods=['GET'], subdomain='dashboard')
@login_required
def donations() -> render_template:
    return render_template('/dashboard/donations.html', user=User().fetch_user_logged_in(), form=DonationSettingsForm(), flashed_message=get_flashed_messages(), donations=Donation().fetch_user_donations())

@dashboard_bp.route('/donations/enable', methods=['GET'], subdomain='dashboard')
@login_required
def enable_donations() -> redirect:
    Setting().donation_toggle(True)
    return redirect(url_for('dashboard.donations'))

@dashboard_bp.route('/donations/disable', methods=['GET'], subdomain='dashboard')
@login_required
def disable_donations() -> redirect:
    Setting().donation_toggle(None)
    return redirect(url_for('dashboard.donations'))

@dashboard_bp.route('/donations/update', methods=['POST'], subdomain='dashboard')
@login_required
def update_donation_settings() -> redirect:
    form = DonationSettingsForm()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('dashboard.donations'))
    
    Setting().update_minimum_amount(request.form)
    
    flash(['Donation settings updated'])
    return redirect(url_for('dashboard.donations'))

@dashboard_bp.route('/products', methods=['GET'], subdomain='dashboard')
@login_required
def products() -> render_template:
    return render_template('/dashboard/products.html', flashed_message=get_flashed_messages(), prods=Product().fetch_user_products())

@dashboard_bp.route('/product/create', methods=['GET'], subdomain='dashboard')
@login_required
def create_product() -> render_template:
    form = ProductForm()
    attachments = Attachment().fetch_user_attachments()

    for item in Category().fetch_user_categories():
        form.categories.choices.append([item.category_name, item.category_name])

    for item in attachments:
        form.attachment_file.choices.append([item.attachment_filename, item.original_attachment_filename])
    
    return render_template('/dashboard/create-product.html', form=form, flashed_message=get_flashed_messages(), attachments=attachments)

@dashboard_bp.route('/product/create/submit', methods=['POST'], subdomain='dashboard')
@login_required
def submit_new_product() -> redirect:
    form = ProductForm()
    attachments = Attachment().fetch_user_attachments()
    
    for item in Category().fetch_user_categories():
        form.categories.choices.append([item.category_name, item.category_name])

    for item in attachments:
        form.attachment_file.choices.append([item.attachment_filename, item.original_attachment_filename])
        
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(url_for('dashboard.create_product'))
   
    Product().add(request)
    
    flash(['Product Successfully Created'])
    return redirect(url_for('dashboard.products'))

@dashboard_bp.route('/product/edit/<string:product_id>', methods=['GET'], subdomain='dashboard')
@login_required
def edit_product(product_id):
    product = Product().fetch_product(product_id, current_user.get_id())
    form = ProductForm()
    
    for item in Category().fetch_user_categories():
        form.categories.choices.append([item.category_name, item.category_name])

    for item in Attachment().fetch_user_attachments():
        form.attachment_file.choices.append([item.attachment_filename, item.original_attachment_filename])
    
    if not product:
        flash(['Something went wrong. Please try again later'])
        return redirect(url_for('dashboard.products'))

    form.product_name.data = product.name
    
    if product.product_type == 'item':
        linked_product_items = ProductItem().fetch_active_product_items(product.product_items)
        form.items.data =  ''.join(linked_product_items)

    else:
        form.attachment_file.data = product.product_attachment.attachment_filename
        form.stock.data = product.stock

    form.price.data = float(product.price)

    return render_template('/dashboard/edit-product.html', product=product, form=form, flashed_message=get_flashed_messages(), attachments=Attachment().fetch_user_attachments())

@dashboard_bp.route('/product/edit/<string:product_id>/submit', methods=['POST'], subdomain='dashboard')
@login_required
def update_product(product_id):
    form = ProductForm()
    attachments = Attachment().fetch_user_attachments()
    
    for item in Category().fetch_user_categories():
        form.categories.choices.append([item.category_name, item.category_name])

    for item in attachments:
        form.attachment_file.choices.append([item.attachment_filename, item.original_attachment_filename])
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])

webapp/routes/order.py
from webapp.forms import PurchaseProduct
from webapp.models import Order, Coupon, User, Product, Attachment
from webapp.payments.paypal import capture_paypal_order, get_paypal_order
from webapp.utils.uploads import download_file
from webapp.utils.tasks import leave_feedback
from flask import Blueprint, request, redirect, url_for, flash, render_template, get_flashed_messages, abort, Response, session
from os import environ

order_bp = Blueprint("order", __name__)

@order_bp.route('/create/order', methods=['POST'])
def create_order() -> redirect:
    form = PurchaseProduct()
    
    if not form.validate_on_submit():
        flash(list(form.errors.values())[0])
        return redirect(request.referrer)

    if request.form.get('coupon_code') != '':
        if not Coupon().check_coupon(request.form):
            flash(['Coupon is invalid. Please try again'])
            return redirect(request.referrer)

    new_order = Order().add(request.form, request.headers.get('User-Agent'))

    if False in new_order:
        flash([new_order[1]])
        return redirect(request.referrer)

    if new_order['payment_method'] == 'paypal':
        return redirect(new_order['payment_address'])
    
    return redirect(url_for('order.track_order', order_id=new_order))

@order_bp.route('/order/<string:order_id>', methods=['GET'])
def track_order(order_id) -> render_template:
    fetch_order = Order().fetch_order(order_id)
    
    if not fetch_order:
        return abort(404)
    
    return render_template('/shop/order.html', order=fetch_order, flashed_message=get_flashed_messages(), user=User().fetch_user_supply_uuid(fetch_order.user), product=Product().fetch_product(fetch_order.product_id, fetch_order.user))

@order_bp.route('/order/payment/complete/<string:order_id>', methods=['GET'])
def payment_complete(order_id):
    ## this needs to be rewritten to take into account stripe and crypto payments
    token = request.args.get('token')
    payer_id = request.args.get('PayerID')
    
    order = Order().fetch_order(order_id)
    
    if not order:
        return abort(404)
    
    if order.payment.transaction_id != token:
        return abort(404)
    
    if order.status != 'Paid':
        capture_paypal_order(token)
        check_order = get_paypal_order(token)
    
        if check_order['payment_status'] == 'COMPLETED':
            order.status = 'Paid'
            deliver_goods = Product().deliver_product(order.product_id, order_id, order.quantity, order.customer.email)
            leave_feedback.apply_async(args=[order.customer.email, User().fetch_user_supply_uuid(order.user).username, order_id, order.order_hash], countdown=120)

        if not order.customer.email:
            order.customer.email = check_order['buyer_email']
        
        order.update()

            
    return redirect(url_for('order.track_order', order_id=order_id))

@order_bp.route('/order/<string:order_id>/download/<string:attachment_id>', methods=['GET'])
def download_attachment(order_id, attachment_id):
    order = Order().fetch_order(order_id)
    
    if (not order) or (order.status != 'Completed'):
        return abort(404)

    attachment = Attachment().fetch_attachment(attachment_id)
    fetch_file = download_file(attachment.attachment_filename, environ.get('AWS_ATTACHMENTS'))
    
    return Response(
            fetch_file['file'],
            mimetype='text/plain',
            headers={"Content-Disposition": f"attachment;filename={attachment.original_attachment_filename}"}
    )

    
    
    
    
    
        
    
    

webapp/routes/payment.py
from webapp.models import User, PaymentMethod
from webapp.payments.stripe import stripe_setup, disconnect_account, account_query
from webapp.utils.login_decorator import login_required
from flask import Blueprint, redirect, url_for, flash, session

payment_bp = Blueprint("payments", __name__)

@payment_bp.route('/stripe/connect', methods=['GET'], subdomain='dashboard')
@login_required
def stripe_connect():
    setup = stripe_setup(User().fetch_user_logged_in.email)
    session['acc_id'] = setup[0]
    
    return redirect(setup[1])

@payment_bp.route('/stripe/connect/validate', methods=['GET'], subdomain='dashboard')
@login_required
def validate_stripe_connect():
    if PaymentMethod().fetch_user_payment_method.stripe:
        return redirect(url_for('dashboard.payment_methods'))

    if account_query(session['acc_id'])['charges_enabled']:
        return redirect(url_for('payments.stripe_success'))
    else:
        flash('Semething went wrong. Please try again later')
        return redirect(url_for('dashboard.payment_methods'))

@payment_bp.route('/stripe/connect/success', methods=['GET'], subdomain='dashboard')
@login_required
def stripe_success():
    PaymentMethod().update_stripe_acc(session['acc_id'])
    session.pop('acc_id')

    flash(['Stripe successfully linked'])
    return redirect(url_for('dashboard.payment_methods'))

@payment_bp.route('/stripe/disconnect', methods=['GET'], subdomain='dashboard')
@login_required
def disconnect_stripe():
    disconnect_account(PaymentMethod().remove_stripe_acc())
    flash(['Stripe Successfully Disconnected'])

    return redirect(url_for('dashboard.payment_methods'))
    

webapp/templates/dashboard/add-blacklist.html
{% extends 'base/dashboard.html' %}
{% set active_page = 'blacklist' %}
{% block title %}Add to Blacklist{% endblock %}
{% block content %}
<div class="dashboard-section-heading">
    <h2>Add Blacklist Entry</h2>
</div>
<div class="create-category-container">
    <form method="POST" action="/blacklist/create/submit">
        <div class="form-control">
            <label for="blacklist_type">
                Type
            </label>
            {{form.blacklist_type}}
        </div>
        <div class="form-control">
            <label for="blocked_data">
                Blocked Data
            </label>
            {{form.blocked_data}}
            {{form.csrf_token}}
        </div>
            <button type="submit" class="btn btn-primary btn-save-coupon">Add Entry</button>
    </form>
</div>
{% endblock %}

webapp/templates/dashboard/attachments.html
{% extends 'base/dashboard.html' %}
{% set active_page = 'attachments' %}
{% block title %}Attachments{% endblock %}
{% block content %}


<div class="dashboard-section-heading">
    <h2>Attachments</h2>
</div>
<div class="upload-attachment">
    <div class="attachment-upload-box">
        <img src="{{url_for('static', filename='img/icons/folder.svg')}}" height="35" width="35">
        <p>Drag & Drop your files</p>
    </div>
</div>
<div class="attachment-upload-form">
    <form method="POST" action="/attachments/upload" enctype="multipart/form-data">
        {{form.attachment_upload(onchange="uploadAttachment()")}}
        {{form.csrf_token}}
        <span id="membership-status" data-membership="{{user.membership.status}}"></span>
        <button type="submit" id="submit-attachment" style="display:none"></button>
    </form>
</div>

{% if attachments.items == [] %}
        <div class="not-yet-created">
                <h2>You currently have no Attachments! :( <br> Drag & Drop your attachment to get started</h2>
        </div>
{% else %}
    <div class="latest-table">
        <div class="table-wrapper">
            <table style="width:100%">
                <tr class="theader">
                    <th class="attachment-name-table">File</th>
                    <th class="attachment-name">Type</th>
                    <th class="attachment-actions">Actions</th>
                </tr>
                {% for item in attachments.items %}
                    <tr class="table-row">
                        <td>{{item.original_attachment_filename}}</td>
                        <td>{{item.attachment_type}}</td>
                        <td>
                            <div class="table-actions">
                                <a href="{{url_for('dashboard.download_attachment', attachment_id=item.id)}}">
                                    <p class="table-action-download">DOWNLOAD</p>
                                </a>
                                <a onclick="inProgress()" href="{{url_for('dashboard.remove_attachment', attachment_id=item.id)}}">
                                    <p class="table-action-delete">DELETE</p>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>  
        <div class="latest-table-view-all">
            {% for page_num in attachments.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                <div class="pagination-numbers">
                    {% if page_num %}
                        {% if attachments.page == page_num %}
                            <a href="{{ url_for('dashboard.attachments', page=page_num)}}" class="active-pagination btn pagination-btn">
                                {{ page_num }}
                            </a>
                        {% else %}
                            <a href="{{ url_for('dashboard.attachments', page=page_num) }}" class="btn pagination-btn"> 
                                {{ page_num }}
                            </a>
                        {% endif %}
                    {% else %}
                    ...
                    {% endif %}
                </div>
                {% endfor %}
        </div>
        
        <p class="showing-of">
            {% if attachments.items != [] %}
                Showing page {{ attachments.page }} of {{ attachments.pages }}
            {% endif %}
        </p>
    </div>
{% endif %}

<span id="attachment-error"></span>
{% endblock %}

webapp/templates/dashboard/donations.html
{% extends 'base/dashboard.html' %}
{% set active_page = 'donations' %}
{% block title %}Donations{% endblock %}
{% block content %}
<div class="donation-header">
    <div class="donation-header-left">
        <h2>Donations</h2>
        <h5>Start Accepting Donations</h5>
    </div>
    <div class="donation-header-right">
        {% if user.settings.donations %}
            <a href="{{url_for('dashboard.disable_donations')}}">
                <button type="button" class="btn btn-donation">DISABLE DONATIONS</button>
            </a>
        {% else %}
            <a href="{{url_for('dashboard.enable_donations')}}">
                <button type="button" class="btn btn-donation btn-donation-enable">ENABLE DONATIONS</button>
            </a>
        {% endif %}
    </div>
</div>

{% if user.settings.donations %}
    <form method="POST" action="/donations/update">
        <div class="donation-settings">
            <h3>Settings</h3>
            <div class="form-control">
                <label for="donation_amount">Minimum Donation Amount</label>
                
                    <div class="inline-flex">
                        <p class="donation-currency">{{user.settings.currency | replace('GBP', '£') | replace('USD', '$') | replace('EUR', '€')}}</p>
                        {{form.amount(class="min-donate-amount", value=user.settings.minimum_donation)}}
                    </div>
            </div>

            <div class="form-control">
                <label for="donation_link">Donation URL</label>
                <input type="text" value="https://sellit.gg/@{{user.username}}/donate" disabled class="donation-url">
                <div class="copy-icon-wrapper">
                    <img src="{{url_for('static', filename='img/icons/copy.svg')}}" height="20" width="20" id="copy-icon">
                </div>
            </div>
            {{form.csrf_token}}
            <button type="submit" class="btn btn-green">Save Settings</button>
        </div>
    </form>
{% endif %}

<div class="latest-table">
    <h3 class="latest-table-heading">
        <img src="{{url_for('static', filename='img/icons/heart.svg')}}" width="20" height="20">
        Donations</h3>
    <div class="table-wrapper">
        <table style="width:100%">
            {% if donations.items == [] %}
                <div class="no-donations">
                    <h3>You haven't received no donations :(</h3>
                </div>
            {% else %}
                <tr class="theader">
                    <th class="donation-name">Name</th>
                    <th class="donation-message">Message</th>
                    <th class="donation-amount">Amount</th>
                    <th class="donation-date">Date</th>
                </tr>
                {% for item in donations.items %}
                    <tr class="table-row">
                        <td>{{item.name}}</td>
                        <td>{% if item.message != None %} {{item.message}} {% endif %}</td>
                        <td>{{user.settings.currency|currency_to_symbol}}{{item.amount}}</td>
                        <td>{{item.timestamp|int|timestamp_to_human}}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div>
    {% if donations.items != [] %}
    <div class="latest-table-view-all">
        {% for page_num in donations.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            <div class="pagination-numbers">
                    {% if page_num %}
                        {% if donations.page == page_num %}
                            <a href="{{ url_for('dashboard.donations', page=page_num)}}" class="active-pagination btn pagination-btn">
                                {{ page_num }}
                            </a>
                        {% else %}
                            <a href="{{ url_for('dashboard.donations', page=page_num) }}" class="btn pagination-btn"> 
                                {{ page_num }}
                            </a>
                        {% endif %}
                    {% else %}
                    ...
                    {% endif %}
            </div>
        {% endfor %}
    </div>
    <p class="showing-of">
        Showing page {{ donations.page }} of {{ donations.pages }}
    </p>
    {% endif %}
</div>
{% endblock %}

webapp/templates/dashboard/payment-methods.html
{% extends 'base/settings.html' %}
{% set active_page = 'settings_payment_methods' %}
{% block settings_block %}
    <h2>Payment Methods</h2>
    <div class="settings-content-wrapper">
        <div class="form-inline">
            <div class="setup-payment-block">
                <div class="inline-setup-block">
                    <h4>Stripe</h4>
                    {% if user.payment_methods.stripe == None %}
                        <a href="{{url_for('payments.stripe_connect')}}">
                            <button type="button" class="btn btn-primary btn-setup-payment">Setup Stripe</button>
                        </a>
                    {% else %}
                        <a href="{{url_for('payments.disconnect_stripe')}}">
                            <button type="button" class="btn btn-primary btn-setup-payment">Disconnect Stripe</button>
                        </a>
                    {% endif %}
                </div>
                <p>Accept Card Payments: Visa, Mastercard and Amex</p>
            </div>
        </div>
        <form method="POST" action="/settings/payment/methods/submit">
            <div class="setup-paypal">
                <h3>PayPal</h3>
                <div class="form-control">
                    <label for="paypal_email">
                        PayPal Email
                    </label>
                    {{form.paypal(placeholder="Your PayPal Email...")}}
                    <div class="paypal_delivery">
                        {{form.paypal_delivery}}
                        <p>Only deliver to Buyer's PayPal Email Address</p>
                    </div>
                </div>
            </div>
            <div class="virtual-address">
                <h3>Virtual Coins</h3>
                <div class="form-control">
                    <label for="bitcoin_address">
                        Bitcoin Address
                    </label>
                    {{form.BTC(placeholder='1B1evZWmaJ26DHrSwFsmaL7TyWEFN72Hfm')}}
                </div>

                <div class="form-control">
                    <label for="ethereum_address">
                        Ethereum Address
                    </label>
                    {{form.ETH(placeholder='0x1Ff482D42D8727258A1686102Fa4ba925C46Bc42')}}
                </div>

                <div class="form-control">
                    <label for="litecoin_address">
                        Litecoin Address
                    </label>
                    {{form.LTC(placeholder='MGxNPPB7eBoWPUaprtX9v9CXJZoD2465zN')}}
                </div>
                {{form.csrf_token}}
                <button type="submit" class="btn btn-primary btn-update-settings">UPDATE PAYMENTS</button>
            </div>
        </form>
    </div>
    </div>
{% endblock %}

webapp/templates/dashboard/products.html
{% extends 'base/dashboard.html' %}
{% set active_page = 'products' %}
{% block title %}Products{% endblock %}
{% block content %}
<div class="dashboard-section-heading">
    <h2>Products Overview</h2>
    <a href="{{url_for('dashboard.create_product')}}">
        <button type="button" class="btn btn-primary create-product">Create Product</button>
    </a>
</div>
{% if prods == [] %}
    <div class="not-yet-created">
            <h2>You currently have no Products! :( <br> Click Create Product to get started</h2>
    </div>
{% else %}

    <div class="latest-table">
        <div class="table-wrapper">
            <table style="width:100%">
                <tr class="theader">
                    <th class="product-name-table">Name</th>
                    <th class="product-name-sku">SKU</th>
                    <th class="donation-amount">Stock</th>
                    <th class="product-name-type">Type</th>
                    <th class="product-actions">Actions</th>
                </tr>
                {% for item in prods %}
                    <tr class="table-row">
                        <td class="overflow-ecllipse">{{item.name}}</td>
                        <td>{{item.id}}</td>
                        <td class="product-stock">{{item.stock}}</td>
                        <td class="product-type">{{item.product_type}}</td>
                        <td>
                            <div class="table-actions">
                                <a href="{{url_for('dashboard.edit_product', product_id=item.id)}}">
                                    <p class="table-action-edit">EDIT</p>
                                </a>
                                <a href="{{url_for('dashboard.delete_product', product_id=item.id)}}">
                                    <p class="table-action-delete">DELETE</p>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>  
        <div class="latest-table-view-all">
            <p class="showing-of">Show 10 of 98 Products</p>
        </div>
    </div>
{% endif %}
{% endblock %}

webapp/templates/dashboard/settings-notification.html
{% extends 'base/settings.html' %}
{% set active_page = 'settings_notifications' %}
{% block settings_block %}
    <h2>Email Notifications</h2>
    <div class="settings-content-wrapper">
        <form method="POST" action="{{url_for('dashboard.update_notification_settings')}}">
            <div class="sub-section">
                <h3>Orders</h3>
                <div class="settings-notification-block">
                    {{form.new_order}}
                    <label for="new_order">New Order</label>
                </div>

                <div class="settings-notification-block">
                    {{form.new_donation}}
                    <label for="new_donation">New Donation</label>
                </div>

                <div class="settings-notification-block">
                    {{form.new_feedback}}
                    <label for="new_donation">New Feedback</label>
                </div>
            </div>
            <div class="sub-section">
                <h3>Support Tickets</h3>
                <div class="settings-notification-block">
                    {{form.new_support_ticket}}
                    <label for="new_donation">New Support Ticket</label>
                </div>

                <div class="settings-notification-block">
                    {{form.support_ticket_reply}}
                    <label for="new_donation">New Support Ticket Reply</label>
                </div>
            </div>
            {{form.csrf_token}}
            <button type="submit" class="btn btn-primary">Save Settings</button>
        </form>
        
    </div>
    </div>
{% endblock %}